version: '2'
services:
  web:
    build: .
    command: bin/rails server --port 3001 --binding 0.0.0.0
    ports:
      - "3001:3001"
    volumes:
      - .:/kafka-consumer-app
networks:
  default:
    external:
      name: kafka-producer-app_default